master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
2024-05-05 21:55:27.892011: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-05 21:55:27.892493: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-05 21:55:27.893272: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-05 21:55:27.898279: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-05 21:55:28.036827: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-05 21:55:28.036990: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-05 21:55:28.038512: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-05 21:55:28.045089: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-05 21:55:28.727000: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-05-05 21:55:28.847129: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
05/05/2024 21:55:38 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False
05/05/2024 21:55:38 - INFO - __main__ - Training/evaluation parameters TrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=True,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
dispatch_batches=None,
do_eval=True,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=20,
evaluation_strategy=steps,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=5,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=True,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=1e-05,
length_column_name=length,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=question_checkpoints_2/runs/May05_21-55-30_venus.cs.northwestern.edu,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=15,
optim=adamw_torch,
optim_args=None,
output_dir=checkpoints/,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=16,
per_device_train_batch_size=16,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['tensorboard'],
resume_from_checkpoint=None,
run_name=question_checkpoints_2/,
save_on_each_node=False,
save_safetensors=False,
save_steps=20,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.0,
)
05/05/2024 21:55:38 - INFO - __main__ - load a local file for train: /home/zck7060/chatguard_1/datasets/questions_labeled/agree_only_all.csv
05/05/2024 21:55:38 - INFO - __main__ - load a local file for validation: /home/zck7060/chatguard_1/datasets/questions_labeled/misaligned_valid.csv
05/05/2024 21:55:38 - INFO - __main__ - load a local file for evaluation: /home/zck7060/chatguard_1/datasets/questions_labeled/filtered_misaligned_evaluate.csv
05/05/2024 21:55:38 - WARNING - __main__ - Process rank: 1, device: cuda:1, n_gpu: 1distributed training: True, 16-bits training: False
05/05/2024 21:55:39 - INFO - datasets.builder - Using custom data configuration default-9ef3a692b03f56b0
05/05/2024 21:55:39 - INFO - datasets.info - Loading Dataset Infos from /home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/packaged_modules/csv
05/05/2024 21:55:39 - WARNING - datasets.builder - Found cached dataset csv (/home/zck7060/.cache/csv/default-9ef3a692b03f56b0/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d)
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:00<00:00, 550.94it/s]
05/05/2024 21:55:39 - WARNING - datasets.builder - Found cached dataset csv (/home/zck7060/.cache/csv/default-9ef3a692b03f56b0/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d)
05/05/2024 21:55:39 - INFO - datasets.info - Loading Dataset info from /home/zck7060/.cache/csv/default-9ef3a692b03f56b0/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:00<00:00, 285.15it/s]
05/05/2024 21:55:39 - INFO - datasets.builder - Using custom data configuration default-aa105d048a2fae80
05/05/2024 21:55:39 - INFO - datasets.info - Loading Dataset Infos from /home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/packaged_modules/csv
05/05/2024 21:55:39 - INFO - datasets.builder - Overwrite dataset info from restored data version if exists.
05/05/2024 21:55:39 - INFO - datasets.info - Loading Dataset info from /home/zck7060/.cache/csv/default-aa105d048a2fae80/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d
05/05/2024 21:55:39 - WARNING - datasets.builder - Found cached dataset csv (/home/zck7060/.cache/csv/default-aa105d048a2fae80/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d)
05/05/2024 21:55:39 - INFO - datasets.info - Loading Dataset info from /home/zck7060/.cache/csv/default-aa105d048a2fae80/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:00<00:00, 828.26it/s]
05/05/2024 21:55:39 - WARNING - datasets.builder - Found cached dataset csv (/home/zck7060/.cache/csv/default-aa105d048a2fae80/0.0.0/eea64c71ca8b46dd3f537ed218fc9bf495d5707789152eb2764f5c78fa66d59d)
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:00<00:00, 979.75it/s]
Traceback (most recent call last):
  File "/home/zck7060/crowdsource_toxicity_classification/noisy_learning_question.py", line 766, in <module>
    main()
  File "/home/zck7060/crowdsource_toxicity_classification/noisy_learning_question.py", line 408, in main
    raw_evaluation_dataset = load_dataset(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/load.py", line 1785, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/load.py", line 1514, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/load.py", line 1143, in dataset_module_factory
    return PackagedDatasetModuleFactory(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/load.py", line 723, in get_module
    data_files = DataFilesDict.from_local_or_remote(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/data_files.py", line 792, in from_local_or_remote
    DataFilesList.from_local_or_remote(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/data_files.py", line 748, in from_local_or_remote
    data_files = resolve_patterns_locally_or_by_urls(base_path, patterns, allowed_extensions)
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/data_files.py", line 348, in resolve_patterns_locally_or_by_urls
Traceback (most recent call last):
  File "/home/zck7060/crowdsource_toxicity_classification/noisy_learning_question.py", line 766, in <module>
    for path in _resolve_single_pattern_locally(base_path, pattern, allowed_extensions):
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/data_files.py", line 292, in _resolve_single_pattern_locally
    raise FileNotFoundError(error_msg)
FileNotFoundError: Unable to find '/home/zck7060/chatguard_1/datasets/questions_labeled/filtered_misaligned_evaluate.csv' at /
    main()
  File "/home/zck7060/crowdsource_toxicity_classification/noisy_learning_question.py", line 408, in main
    raw_evaluation_dataset = load_dataset(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/load.py", line 1785, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/load.py", line 1514, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/load.py", line 1143, in dataset_module_factory
    return PackagedDatasetModuleFactory(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/load.py", line 723, in get_module
    data_files = DataFilesDict.from_local_or_remote(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/data_files.py", line 792, in from_local_or_remote
    DataFilesList.from_local_or_remote(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/data_files.py", line 748, in from_local_or_remote
    data_files = resolve_patterns_locally_or_by_urls(base_path, patterns, allowed_extensions)
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/data_files.py", line 348, in resolve_patterns_locally_or_by_urls
    for path in _resolve_single_pattern_locally(base_path, pattern, allowed_extensions):
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/datasets/data_files.py", line 292, in _resolve_single_pattern_locally
    raise FileNotFoundError(error_msg)
FileNotFoundError: Unable to find '/home/zck7060/chatguard_1/datasets/questions_labeled/filtered_misaligned_evaluate.csv' at /
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2368592) of binary: /home/zck7060/anaconda3/envs/py39/bin/python
Traceback (most recent call last):
  File "/home/zck7060/anaconda3/envs/py39/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zck7060/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
noisy_learning_question.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-05_21:55:40
  host      : venus.cs.northwestern.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2368593)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-05_21:55:40
  host      : venus.cs.northwestern.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2368592)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
